const palette = require(process.cwd() + '/src/styles/masterPaletteData.json')
const fs = require('fs');
const paletteFile = process.cwd() + '/src/styles/__palette.css'
const skinsFile = process.cwd() + '/src/styles/_skins.css'
const header = [
  "/* AUTOGENERATED DO NOT EDIT",
  "   script: yarn generatePalette",
  "   bin: src/utils/generatePalette",
  "   data: ./masterPaletteData */",
  ].join("\n")
// generate __palette.css
let vars = [header]
let skins = [header]
vars.push(":root {")
let groupsSeen = {}
Object.values(palette).forEach(({name, color, group}) => {
  if (!groupsSeen[group]) {
    groupsSeen[group] = true
    vars.push(`\n/* ${group} */`)
    skins.push(`\n/* ${group} */`)
  }
  vars.push(`--${name}: ${color};`)

  skins.push(`.${name} {color: var(--${name});}`)
  skins.push(`.bg-${name} {background-color: var(--${name});}`)
})
vars.push("}\n")
fs.writeFile(paletteFile, vars.join("\n"), err => {
  if (err) console.log(err)
})

// generate _skins.css
fs.writeFile(skinsFile, skins.join("\n"), err => {
  if (err) console.log(err)
})
